[versions]
springBoot = "3.5.16"
springDependencyManagement = "1.1.7"
guava = "33.3.1-jre"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
